# Use postgres/example user/password credentials
# ERRO DO POSTGRES ADMINER
# https://medium.com/@vinjenks/dockerized-local-postgres-and-scram-authentication-a-quick-fix-21c432951bd

version: '3.1'
services:
  db:
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
    build:
      context: ./db
      dockerfile: Dockerfile
    restart: always
    volumes:
      - klimaa_data:/var/lib/postgresql/data

  api:
    environment:
      API_PORT: ${API_PORT}
      API_HOST: ${API_HOST}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: localhost
      DB_PORT: 5432
      DB_DATABASE: ${POSTGRES_DATABASE}
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - ${API_PORT}:${API_PORT}

  nginx:
    environment:
      NGINX_PORT: ${NGINX_PORT}
      NGINX_NAME: ${NGINX_NAME}
      API_PORT: ${API_PORT}
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - api
    ports:
      - ${NGINX_PORT}:80

  modbus_server:
    environment:
      - MODBUS_HOST=${MODBUS_HOST}
      - MODBUS_PORT=${MODBUS_PORT}
    build:
      context: ./modbus_server
      dockerfile: Dockerfile
    ports:
      - ${MODBUS_PORT}:${MODBUS_PORT}

volumes:
  klimaa_data:
